apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  nodeport_port: 32000    # Adjust the port to the port number you wish
  ingress_type: none
  hostname: awx-demo.example.com
  postgres_init_container_resource_requirements: {}
  postgres_data_volume_init: true
