apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-pvc
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Modify the storage size as per your needs
  storageClassName: standard  # Modify the storage class as per your needs
