apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  nodeport_port: 32000
  ingress_type: none
  hostname: awx-demo.example.com
  projects_persistence: true
  projects_existing_claim: awx-pvc
  projects_storage_size: 20Gi
